site_name: Drifter
site_description: 'Drifter simplifies the integration between Unity and Android, enhancing performance seamlessly and effortlessly.'
site_author: 'Teodor Grigor (teogor)'
site_dir: build/docs/improved-system
site_url: 'https://github.com/teogor/drifter'
edit_uri: 'tree/main/docs/'

docs_dir: docs

# Navigation
nav:
  - 'Overview': index.md
  - 'Documentation': documentation
  - 'API Documentation': api-documentation.md
  - 'Sponsor 🩷': sponsor.md
    
# Repository
repo_name: 'drifter'
repo_url: 'https://github.com/teogor/drifter'

# Configuration
theme:
  name: 'material'
  language: 'en'

  palette:
    primary: 'purple'
    accent: 'purple'
    scheme: slate

  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

  features:
    - content.tabs.link  
    - content.code.copy
    - content.code.annotate

extra:
  analytics:
    provider: google
    property: G-XN9N2SV8QZ

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details