name: Build Docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Set configuration cache to false
        run: echo "org.gradle.unsafe.configuration-cache=false" >> $GITHUB_ENV

      - name: Build documentation
        run: ./gradlew -D'org.gradle.unsafe.configuration-cache=false' dokkaHtmlMultiModule

      - name: Set configuration cache to true
        run: echo "org.gradle.unsafe.configuration-cache=true" >> $GITHUB_ENV
